#!/usr/bin/env bash -e

if [ -z $1 ]; then
  echo "usage: release <version>"
  exit 1
fi
version=$1
files="component.json package.json bower.json"
echo "Releasing with version $version"

echo "Pulling from origin"
git pull --rebase

echo "Building"
npm install
npm test
./grunt

echo "Updating files"
sed -i "" 's/\("version".*:.*\)".*"/\1"'$version'"/' $files
sed -i "" 's/<version>/'$version'/' dist/*.js

echo "Commit and tag"
git add .
git commit -m "release $version"
git tag $version

echo "Push to origin/master"
git push
git push --tags origin

echo "Publish to npm"
npm publish

echo "DONE!"
