#!/bin/bash -e

if [ -z $1 ]; then
  echo "usage: release <version>"
  exit 1
fi
version=$1
files="component.json package.json"
echo "Releasing with version $version"

echo "Pulling from origin"
git pull --rebase origin master

echo "Building"
npm install
npm test

echo "Updating files"
sed -i "" 's/\("version".*:.*\)".*"/\1"'$version'"/' $files

echo "Commit and tag"
git add .
git commit -m "release $version"
git tag $version

echo "Push to origin/master"
git push origin master
git push --tags origin master

echo "Publish to npm"
npm publish

echo "DONE!"
