#!/usr/bin/env bash
set -e
./node_modules/.bin/babel-node assemble-specs.js $@

if [ "${TEST_SUITE}" = "browserstack-status" ]; then
  ./node_modules/.bin/grunt browserstack-status
else
  ./node_modules/.bin/mocha --compilers coffee:coffee-script/register spec/BaconSpec.coffee
fi
