#!/usr/bin/env bash -e

npm install --silent

PATH=node_modules/coffee-script/bin:$PATH

coffee src/*.coffee

export grep=$1

./node_modules/mocha/bin/mocha --compilers coffee:coffee-script spec/*Spec.coffee
