#!/usr/bin/env bash -e

if [ -z $1 ]; then
  echo "usage: update-cdnjs <version>"
  exit 1
fi

version=$1
dir=../cdnjs/ajax/libs/bacon.js

if [[ ! -d "$dir/$version" ]]; then
  mkdir $dir/$version
fi

sed -i "" 's/\("version".*:.*\)".*"/\1"'$version'"/' $dir/package.json

git checkout -q $version

cp dist/Bacon.js $dir/$version/bacon.js
cp dist/Bacon.min.js $dir/$version/bacon.min.js

git checkout -q master
