#! /usr/bin/env bash

# generates performance.js for running the performance.html page on your browser

BABEL_ENV=test node_modules/.bin/browserify -d --extension=".coffee" -t coffeeify -t babelify performance/PerformanceTest.coffee > performance/performance.js
