#! /usr/bin/env bash

# generates performance.js for running the performance.html page on your browser

node_modules/.bin/browserify -d --transform coffeeify --extension=".coffee" performance/PerformanceTest.coffee > performance/performance.js
