#!/usr/bin/env bash -e

version=$1
if [ -z $version ]; then
  echo "Enter release version:"
  read version
fi

files="component.json package.json bower.json"
echo "Releasing with version $version"

echo "1. Pulling from origin"
git pull --ff-only --no-rebase origin

echo "2. Building and testing"
npm install
npm test

echo "3. Setting version info to files"
sed -i "" 's/\("version".*:.*\)".*"/\1"'$version'"/' $files
sed -i "" 's/<version>/'$version'/' dist/*.js

echo "4. Commit and tag"
git add .
git commit -m "release $version"
git tag $version

echo "5. Push to origin/master"
git push
git push --tags origin

echo "6. Publish to npm"
npm publish

echo "DONE! Released version $version"
