#!/usr/bin/env bash
set -e
echo TEST_SUITE=$TEST_SUITE
if [ ! -z $DEBUG ]; then
  DEBUG="debug"
fi
if [ "${TEST_SUITE}" = "browserstack" ]; then
  echo "building browser test suite"
  npm run browsertest-bundle
  echo "running on browserstack"
  npm run browserstack
else
  ./node_modules/.bin/mocha $DEBUG -r ts-node/register --files test/*.ts test/notinbrowser/*.ts
fi
