// build-dependencies: awaiting
// build-dependencies: boolean
// build-dependencies: buffer
// build-dependencies: bufferingthrottle
// build-dependencies: bus
// build-dependencies: callback
// build-dependencies: combine
// build-dependencies: combinetemplate
// build-dependencies: concat
// build-dependencies: core
// build-dependencies: debounce
// build-dependencies: decode
// build-dependencies: delay
// build-dependencies: diff
// build-dependencies: doaction
// build-dependencies: doerror
// build-dependencies: dolog
// build-dependencies: endonerror
// build-dependencies: errors
// build-dependencies: factories
// build-dependencies: frompromise
// build-dependencies: flatmap
// build-dependencies: flatmapconcat
// build-dependencies: flatmaperror
// build-dependencies: flatmaplatest
// build-dependencies: flatmapwithconcurrencylimit
// build-dependencies: fold
// build-dependencies: frompoll
// build-dependencies: groupby
// build-dependencies: holdwhen
// build-dependencies: interval
// build-dependencies: jquery
// build-dependencies: later
// build-dependencies: log
// build-dependencies: maperror
// build-dependencies: mapend
// build-dependencies: merge
// build-dependencies: once
// build-dependencies: repeatedly
// build-dependencies: retry
// build-dependencies: sample
// build-dependencies: scan
// build-dependencies: sequentially
// build-dependencies: skip
// build-dependencies: skipduplicates
// build-dependencies: skiperrors
// build-dependencies: skipuntil
// build-dependencies: skipwhile
// build-dependencies: slidingwindow
// build-dependencies: spy
// build-dependencies: startwith
// build-dependencies: take
// build-dependencies: takewhile
// build-dependencies: takeuntil
// build-dependencies: update
// build-dependencies: when
// build-dependencies: zip

// ES6 pieces:
// build-dependencies: first
// build-dependencies: last
// build-dependencies: throttle
// build-dependencies: topromise
